language: bash
dist: xenial
services: docker

addons:
  apt:
    packages:
      - docker-ce
    update: true

env:
  - image=ad-insertion/video-analytics-service
  - image=ad-decision
  - image=image/ffmpeg
  - image=account
  - image=ad-content/frontend
  - image=ad-content/archive
  - image=ad-insertion/frontend
  - image=ad-insertion/ad-static
  - image=ad-insertion/analytic-db
  - image=ad-insertion/ad-transcode
  - image=deployment
  - image=cdn
  - image=content-provider/transcode
  - image=content-provider/frontend
  - image=content-provider/archive

before_install:
  - docker version

script:
  - echo image=${image}
  - if [ ${image} = ad-insertion/video-analytics-service ]; then
      echo hello 2.1;
      else
        echo hello 2.2;
      fi

after_success:
  - echo after success staging ....
  - echo image=${image}
  - if [ ${image} = ad-insertion/video-analytics-service ]; then 
      echo hello 3;
    fi
  
