language: bash
dist: xenial
services: docker
addons:
  apt:
    packages:
      - docker-ce
    update: true
env:
  - CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg
  - CPU=Xeon buildOS=centos-7.6 imageName=dldt+gst
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=ospray
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=ospray+mpi+OpenImageIO

before_install:
  - docker version
script:
  - echo Building ${CPU}/${buildOS}/${imageName}

#matrix:
job:
  include:
    # centos-7.4 job
    - name: centos-7.4/ffmpeg+gst+dev
      env: CPU=Xeon buildOS=centos-7.4 imageName=ffmpeg+gst+dev
      script:
        - echo Building ${CPU}/${buildOS}/${imageName}
      after_failure:
        - tail --lines=5000 log_Xeon_centos74_ffmpeg_gst_dev.log
